"""empty message

Revision ID: 11748ebe3f9c
Revises: d2d937683642
Create Date: 2018-06-27 21:44:29.553728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11748ebe3f9c'
down_revision = 'd2d937683642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_published')
    # ### end Alembic commands ###
