"""empty message

Revision ID: a17d011b3e1e
Revises: 1e55967b4949
Create Date: 2018-06-24 12:07:48.680425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17d011b3e1e'
down_revision = '1e55967b4949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('year_published', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('articles', sa.Column('book_id', sa.Integer(), nullable=True))
    op.drop_constraint('articles_book_title_key', 'articles', type_='unique')
    op.create_foreign_key(None, 'articles', 'books', ['book_id'], ['id'])
    op.drop_column('articles', 'book_author')
    op.drop_column('articles', 'book_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('book_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('book_author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_unique_constraint('articles_book_title_key', 'articles', ['book_title'])
    op.drop_column('articles', 'book_id')
    op.drop_table('books')
    # ### end Alembic commands ###
