"""empty message

Revision ID: c304373b1ee8
Revises: a17d011b3e1e
Create Date: 2018-06-24 12:54:57.471242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c304373b1ee8'
down_revision = 'a17d011b3e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'articles', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
