"""empty message

Revision ID: d2d937683642
Revises: c304373b1ee8
Create Date: 2018-06-24 17:55:40.685776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d937683642'
down_revision = 'c304373b1ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('path')
    )
    op.add_column('articles', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'uploaded_images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'image_id')
    op.drop_table('uploaded_images')
    # ### end Alembic commands ###
